### PR TITLE
Improve Performance of Monte Carlo Function creation

### PR DESCRIPTION
**Pull request by lrennels**
#15 
- Replace `findall` with faster indexing methods and be careful about order
- Improve performance so that the creation of the mcs function is not scaling so linearly with `n` 
- Still room for improvement using `view` instead of allocating using slices

### CODE REVIEW

**Comment by lrennels** [comment]
@jrising this should help with speed, but I have goals of making it even better :) ... this removes a bunch of extra indexing and memory allocation that on my end seemed to really improve things

**Comment by jrising** [comment]
Thanks!

**Comment by jrising** [comment]
Oddly, this did not make a big change for me. Here's the @time on an SCC Monte Carlo (100 iterations) before the change:
```
 67.299299 seconds (450.60 M allocations: 38.127 GiB, 31.87% gc time, 28.92% compilation time)
```
and here it is after the change:
```
 63.453328 seconds (451.99 M allocations: 39.085 GiB, 25.36% gc time, 26.50% compilation time)
```
It looks like actually a little more memory was allocated.

This could reflect other changes that I've made to this FAIR MC function.

**Comment by lrennels** [comment]
Ah interesting thanks @jrising, for my runs I was testing some convergence so my focus was bringing down the huge increase in time when running an `n` of 100 --> 1000 --> 10000 so perhaps it didn't help much for the lower values and mostly focused on that problem. 

Extra allocation might have been a trade off for removing slices within the loop over `n`. 

More than happy to take a look when I get back and do some more profiling, it may be that I just need to take some of this pre-processing and create better formatted CSV files, which we'd need for this Monte Carlo but also for a Mimi version of a Monte Carlo. 

I can time mine today and let you know!

**Comment by jrising** [comment]
Also looking at my numbers, I realize that I should complain so much about having to wait 60 seconds for the model to compile. It just always felt a lot longer.

**Comment by lrennels** [comment]
No worries we can always improve it!  At least now it will scale more nicely with n though :)

**Pull request merged**
